query GetFollowingUsers(
  $followingId: String!
) {
  users(
    followingId: $followingId
  ) {
    totalCount
    nodes {
      name
      countFollower
    }
    pageInfo{
      hasNextPage
    }
  }
}
