query GetFollowerUsers(
  $followerId: String!
  $perPage: Int
  $page: Int
) {
  users(
    followerId: $followerId
    perPage: $perPage
    page: $page
  ) {
    totalCount
    nodes {
      ...UserFull
    }
    pageInfo{
      hasNextPage
    }
  }
}
