query GetFollowingUsers(
  $followingId: String!
  $perPage: Int
  $page: Int
) {
  users(
    followingId: $followingId
    perPage: $perPage
    page: $page
  ) {
    totalCount
    nodes {
      ...UserFull
    }
    pageInfo{
      hasNextPage
    }
  }
}
