query GetFollowerUsers(
  $followerId: String!
) {
  users(
    followerId: $followerId
  ) {
    totalCount
    nodes {
      name
      countFollower
    }
    pageInfo{
      hasNextPage
    }
  }
}
