fragment PostDetail on Post {
  id
  title
  user {
    ...UserFull
  }
  contents
  category {
    id
    label
  }
  createAt
  updateAt
  activeAt
}

query GetPost(
  $id: ID!
) {
  getPost(
    id: $id
  ) {
    ...PostDetail
  }
}
