query GetPost(
  $id: ID!
) {
  getPost(
    id: $id
  ) {
    title
    user {
      id
      name
      countFollower
      countPost
    }
    contents
    category {
      id
      label
    }
    createAt
    updateAt
    activeAt
  }
}
