fragment PostInPage on Post {
  id
  title
  countLike
  isLike
  user {
    id
    name
  }
  category {
    id
    label
  }
}

query PostPagination(
    $perPage: Int
    $page: Int
    $likeUserId: String
    $userId: String
    $query: String
    $categoryId: String
) {
    posts(
      pageOptions: {
        perPage: $perPage
        page: $page
      }
      postOptions: {
        likeUserId: $likeUserId
        userId: $userId
        categoryId: $categoryId
        query: $query
      }
    ) {
      totalCount
      nodes {
        ...PostInPage
      }
      pageInfo {
        hasNextPage
      }
    }
}