fragment PostInPage on Post {
  id
  title
  countLike
  isLike
  user {
    id
    name
  }
  category {
    id
    label
  }
  countComment
}

query PostPagination(
    $perPage: Int
    $page: Int
    $likeUserId: String
    $userId: String
    $query: String
    $categoryId: String
    $order: PostOrder
    $asc: Boolean
) {
    posts(
      perPage: $perPage
      page: $page
      likeUserId: $likeUserId
      userId: $userId
      categoryId: $categoryId
      query: $query
      order: $order
      asc: $asc
    ) {
      totalCount
      nodes {
        ...PostInPage
      }
      pageInfo {
        hasNextPage
      }
    }
}